version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv nasa
            . nasa/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "nasa"
      - run:
          name: Running tests
          command: |
            . nasa/bin/activate
            python3 tests.python
      - store_artificats:
          path: test-reports/
          destination: python_app
      

